<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class CreateSmLanguagePhrasesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sm_language_phrases', function (Blueprint $table) {
            $table->increments('id');
            $table->collation = 'utf8_general_ci';
            $table->charset = 'utf8';
            $table->text('modules')->nullable();
            $table->text('default_phrases')->nullable();
            $table->text('en')->nullable();
            $table->tinyInteger('active_status')->default('1');
            $table->timestamps();
        });
        $all_translate = [
            [NULL, 0, 'send_email', 'Send email'],
            [NULL, 0, 'send_through', 'Send through'],
            [NULL, 0, 'select_all', ' Select all'],
            [NULL, 0, 'promotional', ' Promotional'],
            [NULL, 0, 'deactive', ' Deactive '],
            [NULL, 0, 'dashboard', ' Dashboard '],
            [NULL, 0, 'feedback', ' Feedback '],
            [NULL, 0, 'reject', ' Reject '],
            [NULL, 0, 'support', ' Support '],
            [NULL, 0, 'welcome', ' Welcome '],
            [NULL, 0, 'user', ' User'],
            [NULL, 0, 'uplaod', ' Uplaod'],
            [NULL, 0, 'vendor', 'Vendor'],
            [NULL, 0, 'customer', 'Customer'],
            [NULL, 0, 'management', 'Management'],
            [NULL, 0, 'list', 'List'],
            [NULL, 0, 'name', 'Name'],
            [NULL, 0, 'email', 'Email'],
            [NULL, 0, 'verify', 'Verify'],
            [NULL, 0, 'expiring', 'Expiring'],
            [NULL, 0, 'status', 'Status'],
            [NULL, 0, 'search', 'Search'],
            [NULL, 0, 'close', 'Close'],
            [NULL, 0, 'humanresource', 'Human Resource'],
            [NULL, 0, 'action', 'Action'],
            [NULL, 0, 'select', 'Select'],
            [NULL, 0, 'view', 'View'],
            [NULL, 0, 'edit', 'Edit'],
            [NULL, 0, 'delete', 'Delete'],
            [NULL, 0, 'total', 'Total'],
            [NULL, 0, 'balance', 'Balance'],
            [NULL, 0, 'earning', 'Earning'],
            [NULL, 0, 'active', 'Active'],
            [NULL, 0, 'pending', 'Pending'],
            [NULL, 0, 'Attachment', 'Attachment'],
            [NULL, 0, 'reply', 'Reply'],
            [NULL, 0, 'department', 'Department'],
            [NULL, 0, 'priority', 'Priority'],
            [NULL, 0, 'suspended', 'Suspended'],
            [NULL, 0, 'permission', 'Permission'],
            [NULL, 0, 'login', 'Login'],
            [NULL, 0, 'enter_login', 'Enter Login details to get access'],
            [NULL, 0, 'success_alert', 'Success'],
            [NULL, 0, 'failed_alert', 'Error'],
            [NULL, 0, 'success_message', 'Operation success !'],
            [NULL, 0, 'failed_message', 'Operation failed !'],
            [NULL, 0, 'Date_of_birth', 'Date of birth'],
            [NULL, 0, 'first', 'First'],
            [NULL, 0, 'last', 'Last'],
            [NULL, 0, 'number_of_sale', 'number of sale'],
            [NULL, 0, 'days', 'days'],
            [NULL, 0, 'extend_buyer_Fee	', 'Extend Buyer Fee'],
            [NULL, 0, 'regular_buyer_Fee	', 'Regular Buyer Fee'],
            [NULL, 0, 'today', 'today'],
            [NULL, 0, 'fund_deposit', 'Fund Deposit'],
            [NULL, 0, 'paid', 'Paid'],
            [NULL, 0, 'one', 'One'],
            [NULL, 0, 'six', 'Six'],
            [NULL, 0, 'full', 'Full'],
            [NULL, 0, 'online', 'Online'],
            [NULL, 0, 'print', 'Print'],
            [NULL, 0, 'father', 'Father'],
            [NULL, 0, 'mother', 'Mother'],
            [NULL, 0, 'mobile', 'Mobile'],
            [NULL, 0, 'information', 'Information'],
            [NULL, 0, 'reset', 'Reset'],
            [NULL, 0, 'Current_address', 'Current address'],
            [NULL, 0, 'Permanent_addres', 'Permanent addres'],
            [NULL, 0, 'location', 'Location'],
            [NULL, 0, 'update', 'Update'],
            [NULL, 0, 'date_of_joining', 'Date of joining'],
            [NULL, 0, 'browse', 'Browse'],
            [NULL, 0, 'image_upload_requirement_100', 'Only PNG 100x100PX'],
            [NULL, 0, 'Crop_Image_And_Upload', 'Crop Image And Upload'],
            [NULL, 0, 'No_file_selected', 'No file selected'],
            [NULL, 0, 'basic_info', 'Basic information'],
            [NULL, 0, 'image_upload_400', 'JPG OR PNG 860x400PX'],
            [NULL, 0, 'acknowledgement_for_Terms_of_Service', 'You have read and agree to HostGator Terms of Service and Cancellation Policy and acknowledge receipt of the Privacy Policy.'],
            [NULL, 0, 'instruction_for_terms_and_conditions', 'By clicking "Checkout Now" you agree to have your personal information transferred and stored in the United States, which is necessary to provide you with the services under our agreement with you.'],
            [NULL, 0, 'payment', 'Payment'],
            [NULL, 0, 'click', 'Click'],
            [NULL, 0, 'new', 'New'],
            [NULL, 0, 'extent_support_time', 'Extend support to 12 months.'],
            [NULL, 0, 'info', 'Info'],
            [NULL, 0, 'method', 'Method'],
            [NULL, 0, 'Product', 'Product'],
            [NULL, 0, 'profile', 'Profile'],
            [NULL, 0, 'category', 'Category'],
            [NULL, 0, 'save', 'Save'],
            [NULL, 0, 'description', 'Description'],
            [NULL, 0, 'upload_photo', 'Upload Photo'],
            [NULL, 0, 'upload_icon', 'Upload Icon'],
            [NULL, 0, 'icon', 'Icon'],
            [NULL, 0, 'image', 'Image'],
            [NULL, 0, 'add', 'Add'],
            [NULL, 0, 'inactive', 'Inactive'],
            [null, 0, 'cancel', 'Cancel'],
            [null, 0, 'level', 'Level'],
            [null, 0, 'sub', 'Sub'],
            [null, 0, 'are_you_sure_to_delete', 'Are you sure to delete?'],
            [null, 0, 'are_you_sure_to_active', 'Are you sure to active?'],
            [null, 0, 'knowledge_base', 'Knowledge Base'],
            [null, 0, 'attributes', 'Attributes'],
            [null, 0, 'field_name', 'Field Name'],
            [null, 0, 'fee', 'Fee'],
            [null, 0, 'buyer', 'Buyer'],
            [null, 0, 'buy', 'Buy'],
            [null, 0, 'emails', 'emails'],
            [null, 0, 'daily', 'Daily'],
            [null, 0, 'summary', 'summary'],
            [null, 0, 'daily_summary_emails', 'Send me a daily summary of all items approved or rejected'],
            [null, 0, 'buyer_review_notifications', 'Send an email reminding me to rate an item a week after purchase'],
            [null, 0, 'type', 'Type'],
            [null, 0, 'regular', 'Regular'],
            [null, 0, 'up', 'Up'],
            [null, 0, 'file', 'File'],
            [null, 0, 'yes', 'Yes'],
            [null, 0, 'no', 'No'],
            [null, 0, 'title', 'Title'],
            [null, 0, 'price', 'Price'],
            [null, 0, 'demo', 'Demo'],
            [null, 0, 'url', 'Url'],
            [null, 0, 'label', 'Lavel'],
            [null, 0, 'badge', 'Badge'],
            [null, 0, 'amount', 'Amount'],
            [null, 0, 'time', 'Time'],
            [null, 0, 'password', 'Password'],
            [null, 0, 'admin', 'Admin'],
            [null, 0, 'website', 'Website'],
            [null, 0, 'reports', 'Reports'],
            [null, 0, 'member', 'Member'],
            [null, 0, 'plan', 'Plan'],
            [null, 0, 'package', 'Package'],
            [null, 0, 'log', 'Log'],
            [null, 0, 'log', 'Log'],
            [null, 0, 'device', 'Device'],
            [null, 0, 'coupon', 'Coupon'],
            [null, 0, 'code', 'Code'],
            [null, 0, 'discount', 'Discount'],
            [null, 0, 'valid', 'Valid'],
            [null, 0, 'enter', 'Enter'],
            [null, 0, 'date', 'Date'],
            [null, 0, 'id', 'id'],
            [null, 0, 'min_price', 'Min Price'],
            [NULL, 0, 'details', 'Details'],
            [null, 1, 'system_settings', 'System Settings'],
            [null, 1, 'email_settings', 'Email Settings'],
            [null, 1, 'payment_method', 'Payment Method'],
            [null, 1, 'setting', 'Setting'],
            [null, 1, 'Order', 'Order'],
            [null, 1, 'configuration', 'Configuration'],
            [null, 1, 'setup', 'Setup'],
            [null, 1, 'language', 'Language'],
            [null, 1, 'select_language', 'Select Language'],
            [null, 1, 'status', 'Status'],
            [null, 1, 'universal', 'Universal'],
            [null, 1, 'native', 'Native'],
            [null, 1, 'remove', 'Remove'],
            [null, 1, 'seo', 'SEO'],
            [null, 1, 'site', 'Site'],
            [null, 1, 'google', 'Google'],
            [null, 1, 'system_setting', 'System Setting'],
            [null, 1, 'pages', 'Pages'],
            [null, 1, 'about', 'About'],
            [null, 1, 'company', 'Company'],
            [null, 1, 'KnowledgeBase', 'Knowledge Base'],
            [null, 1, 'deleteWarningQuestion', 'If you delete this question, the system will delete all related data'],
            [null, 1, 'deleteWarning', 'If you delete this category, the system will delete all related data'],
            [null, 1, 'sub', 'Sub'],
            [null, 1, 'privacy', 'Privacy'],
            [null, 1, 'history', 'History'],
            [null, 1, 'policy', 'Policy'],
            [null, 1, 'terms', 'Terms'],
            [null, 1, 'conditions', 'Conditions'],
            [null, 1, 'short', 'Short'],
            [null, 1, 'heading', 'Heading'],
            [null, 1, '&', '&'],
            [null, 0, 'role', 'Role'],
            [null, 1, 'faq', 'FAQ'],
            [null, 1, 'faqs', 'FAQs'],
            [null, 1, 'question', 'Question'],
            [null, 1, 'answers', 'Answers'],
            [null, 1, 'answer', 'Answer'],
            [null, 1, 'is_configure_require', 'Is Configure Require'],
            [NULL, 20, 'primary_color', 'Primary Color'],
            [NULL, 20, 'primary_color2', 'Primary Color 2'],
            [NULL, 20, 'primary_color3', 'Primary Color 3'],
            [NULL, 20, 'title_color', 'Title Color'],
            [NULL, 20, 'text_color', 'Text Color'],
            [NULL, 20, 'sidebar_bg', 'Sidebar'],
            [NULL, 20, 'theme', 'Theme'],
            [NULL, 20, 'background', 'Background'],
            [NULL, 20, 'style', 'Style'],
            [NULL, 20, 'color', 'Color'],
            [NULL, 20, 'change', 'Change'],
            [NULL, 20, 'saved', 'Saved'],
            [NULL, 20, 'changes', 'Changes'],
            [NULL, 20, 'system_name', 'System Name'],
            [NULL, 20, 'system_title', 'System Title'],
            [NULL, 20, 'address', 'Address'],
            [NULL, 20, 'keep_me_logged_in', 'Keep me logged in'],
            [NULL, 20, 'phone', 'Phone',],
            [NULL, 20, 'currency', 'Currency',],
            [NULL, 20, 'currency_symbol', 'Currency Symbol'],
            [NULL, 20, 'currency_code', 'Currency Code'],
            [NULL, 20, 'time_zone', 'Time Zone'],
            [NULL, 20, 'copyright_text', 'Copyright Text'],
            [NULL, 20, 'amazons3_host', 'Amazons3 Host'],
            [NULL, 20, 'module_manage', 'Module Manage'],
            [NULL, 20, 'Amazon_S3', 'Amazon S3'],
            [NULL, 20, 'Next_Payout', 'Next Payout'],
            [NULL, 20, 'You_currently_have', 'You currently have'],
            [NULL, 20, 'setup_aws3', 'Setup AWS3'],
            [NULL, 20, 'language_name', 'Language Name'],
            [NULL, 20, 'default', 'Default'],
            [NULL, 20, 'commercial', 'Commercial'],
            [NULL, 20, 'commercial_buyer_Fee', 'Com Buyer Fee'],
            [NULL, 20, 'next_month_payout', 'in earnings for next month payout'],
            [NULL, 20, 'make_default', 'Make Default'],
            [NULL, 20, 'sl', 'Sl'],
            [NULL, 20, 'from_name', 'From Name'],
            [NULL, 20, 'from', 'From'],
            [NULL, 20, 'mail', 'Mail'],
            [NULL, 20, 'driver', 'Driver'],
            [NULL, 20, 'host', 'Host'],
            [NULL, 20, 'port', 'Port'],
            [NULL, 20, 'your_bank_account', 'Your Bank Account'],
            [NULL, 20, 'google_analytics', 'GOOGLE ANALYTICS'],
            [NULL, 20, 'public_vendor_registration', 'Public Vendor Registration'],
            [NULL, 20, 'product_upload', 'Product Upload'],
            [NULL, 20, 'purchase_link', 'Purchase Link'],
            [NULL, 20, 'product_upload_or_link', 'Product Upload Or Link'],
            [NULL, 20, 'google_analytics_warning', 'Complete Google Analytics Setup to view this graphical statistics data or you can hide those from'],
            [NULL, 20, 'username', 'Username'],
            [NULL, 20, 'encryption', 'Encryption'],
            [NULL, 20, 'method_name', 'Method Name'],
            [NULL, 20, 'env_terms', 'Key'],
            [NULL, 20, 'env_value', 'Value'],
            [NULL, 20, 'faq', 'Frequently Asked Questions'],
            [NULL, 20, 'language_settings', 'Language Settings'],
            [NULL, 20, 'background_settings', 'Background Settings'],
            [NULL, 20, 'footer_setting', 'Footer Setting'],
            [NULL, 20, 'general_settings', 'General Setting'],
            [NULL, 20, 'language_setup', 'Language Setup'],
            [NULL, 20, 'update_language', 'Update Language'],
            [NULL, 20, 'logo', 'Logo'],
            [NULL, 20, 'status', 'Status'],
            [NULL, 20, 'facebook_link', 'Facebook Link'],
            [NULL, 20, 'twitter_link', 'Twitter Link'],
            [NULL, 20, 'author', 'Author'],
            [NULL, 20, 'keyword', 'Keyword'],
            [NULL, 0, 'purchases', 'purchases'],
            [NULL, 0, 'purchase', 'purchase'],
            [NULL, 0, 'make', 'Make'],
            [NULL, 0, 'followers', 'Followers'],
            [NULL, 0, 'Following', 'Following'],
            [NULL, 0, 'followings', 'Followings'],
            [NULL, 0, 'see', 'see'],
            [NULL, 0, 'awating', 'Awating'],
            [NULL, 0, 'review', 'Review'],
            [NULL, 0, 'item_revirew_notification ', 'Send an email reminding me to rate an item a week after purchase'],
            [NULL, 0, 'personal', 'Personal'],
            [NULL, 0, 'credit', 'Credit'],
            [NULL, 0, 'number', 'number'],
            [NULL, 0, 'holder', 'Holder'],
            [NULL, 0, 'current', 'Current'],
            [NULL, 0, 'card', 'Card'],
            [NULL, 0, 'cvc', 'Cvc'],
            [NULL, 0, 'assignee', 'Assignee'],
            [NULL, 0, 'expiration', 'Expiration'],
            [NULL, 0, 'mm', 'MM'],
            [NULL, 0, 'yy', 'YY'],
            [NULL, 0, 'preview', 'Preview'],
            [NULL, 0, 'social', 'social'],
            [NULL, 0, 'network', 'network'],
            [NULL, 0, 'networks', 'networks'],
            [NULL, 0, 'banner', 'Banner'],
            [NULL, 0, 'install', 'Install'],
            [NULL, 20, 'total',      'Total'],
            [NULL, 20, 'product',    'Product'],
            [NULL, 20, 'products',   'Products'],
            [NULL, 20, 'approval',   'Approval'],
            [NULL, 20, 'pending',    'Pending'],
            [NULL, 20, 'sale',       'Sale'],
            [NULL, 20, 'withdraws',  'Withdraws'],
            [NULL, 20, 'customers',  'Customers'],
            [NULL, 20, 'subscribers', 'Subscribers'],
            [NULL, 20, 'vendors',    'Vendors'],
            [NULL, 20, 'users',    'Users'],
            [NULL, 20, 'blocked',    'Blocked'],
            [NULL, 20, 'free',    'Free'],
            [NULL, 20, 'subscribers',    'Subscribers'],
            [NULL, 20, 'mark_all_as_read',    'Mark All As Read'],
            [NULL, 20, 'are_you_sure_to_remove',    'Are you sure to remove?'],
            [NULL, 20, 'blog', 'Blog'],
            [NULL, 20, 'subscription', 'Subscription'],
            [NULL, 20, 'newsletter', 'Newsletter'],
            [NULL, 20, 'registered', 'Registered'],
            [NULL, 20, 'register', 'Register'],
            [NULL, 20, 'rate', 'Rate'],
            [NULL, 20, 'registration', 'Registration'],
            [NULL, 20, 're_captcha', 'Recaptcha'],
            [NULL, 20, 'bonus', 'Bonus'],
            [NULL, 20, 'confirm', 'Confirm'],




            [NULL, 20, 'notification',    'Notification'],
            [NULL, 20, 'you_have',    'You Have'],
            [NULL, 20, 'upload',    'Upload'],
            [NULL, 20, 'AddOns',    'Add Ons'],

            [NULL, 20, 'review ', 'Review'],
            [NULL, 20, 'item ', 'Item'],
            [NULL, 20, 'monthly ', 'Monthly'],
            [NULL, 20, 'half_yearly ', 'Half Yearly'],
            [NULL, 20, 'yearly ', 'Yearly'],


            [NULL, 20, 'filter', 'Filter'],
            [NULL, 20, 'sales', 'Sales'],
            [NULL, 20, 'no', 'No'],
            [NULL, 20, 'high', 'High'],
            [NULL, 20, 'mudium', 'Mudium'],
            [NULL, 20, 'low', 'Low'],
            [NULL, 20, 'star_and_higher', 'Star and Higher'],
            [NULL, 20, 'top_seller', 'Top Seller'],
            [NULL, 20, 'sell', 'Sell'],
            [NULL, 20, 'date', 'Date'],
            [NULL, 20, 'added', 'Added'],
            [NULL, 20, 'any', 'Any'],
            [NULL, 20, 'year', 'year'],
            [NULL, 20, 'month', 'month'],
            [NULL, 20, 'Trending', 'Trending'],
            [NULL, 20, 'Rated', 'Rated'],
            [NULL, 20, 'Newest', 'Newest'],
            [NULL, 20, 'Sellers', 'Sellers'],
            [NULL, 20, 'all_items', 'All items'],
            [NULL, 20, 'Sub', 'Sub'],
            [NULL, 20, 'Category', 'Category'],
            [NULL, 20, 'Tags', 'Tags'],
            [NULL, 20, 'Price', 'Price'],
            [NULL, 20, 'rating', 'Rating'],
            [NULL, 20, 'following', 'Following'],
            [NULL, 20, 'no_rating_yet', 'No rating yet'],
            [NULL, 20, 'mryr', 'main reason for your rating'],
            [NULL, 20, 'week', 'week'],
            [NULL, 20, 'not_yet', 'Not yet'],
            [NULL, 20, 'Best', 'Best'],
            [NULL, 20, 'Pricing', 'Pricing'],
            [NULL, 20, 'Plans', 'Plans'],
            [NULL, 20, 'software', 'Software'],
            [NULL, 20, 'Infix', 'Infix'],
            [NULL, 20, 'Files', 'Files'],
            [NULL, 20, 'Included', 'Included'],
            [NULL, 20, 'Columns', 'Columns'],
            [NULL, 20, 'Documentation', 'Documentation'],
            [NULL, 20, 'Well', 'Well'],
            [NULL, 20, 'Documented', 'Documented'],
            [NULL, 20, 'Layout', 'Layout'],
            [NULL, 20, 'License', 'License'],
            [NULL, 20, 'license', 'License'],
            [NULL, 20, 'Customize_your_selection', 'Customize Your Selection'],
            [NULL, 20, 'Select_a_License', 'Select a License'],
            [NULL, 20, 'version', 'Version'],
            [NULL, 20, 'forgot', 'Forgot'],
            [NULL, 20, 'Regular', 'Regular'],
            [NULL, 20, 'Extended', 'Extended'],
            [NULL, 20, 'Available', 'Available'],
            [NULL, 20, 'Packages', 'Packages'],
            [NULL, 20, 'Billing', 'Billing'],
            [NULL, 20, 'Information', 'Information'],
            [NULL, 20, 'Father', 'Father'],
            [NULL, 20, 'Mother', 'Mother'],
            [NULL, 20, 'Checkout', 'Checkout'],
            [NULL, 20, 'Now', 'Now'],
            [NULL, 20, 'Amount', 'Amount'],
            [NULL, 20, 'Due', 'Due'],
            [NULL, 20, 'cancle', 'cancle'],
            [NULL, 20, 'comments', 'Comments'],
            [NULL, 20, 'product_review_by_buyer', 'Product review by buyer'],
            [NULL, 20, 'review_publish_to_other', 'your review will be publicaly visible and the author may replay to your comments'],
            [NULL, 20, 'Total', 'Total'],
            [NULL, 20, 'Downloads', 'Downloads'],
            [NULL, 20, 'Ratings', 'Ratings'],
            [NULL, 20, 'pinterest_link', 'Pinterest Link'],
            [NULL, 20, 'youtube_link', 'Youtube Link'],
            [NULL, 20, 'instagram_link', 'Instagram Link'],
            [NULL, 20, 'social', 'Social'],
            [NULL, 20, 'profiles', 'Profiles'],
            [NULL, 20, 'average_based_on', 'average based on'],
            [NULL, 20, 'comment', 'Comment'],
            [NULL, 20, 'overview', 'Overview'],
            [NULL, 20, 'reviews', 'Reviews'],
            [NULL, 20, 'Support', 'Support'],
            [NULL, 20, 'duration', 'duration'],
            [NULL, 20, 'months', 'Months'],
            [NULL, 20, 'Replay', 'Replay'],
            [NULL, 20, 'Post', 'Post'],
            [NULL, 20, 'Features', 'Features'],
            [NULL, 20, 'Last', 'Last'],
            [NULL, 20, 'author_response_time_message', 'This author response time can be up to 1 business day.'],
            [NULL, 20, 'pqfthi', 'Popular questions for this item'],
            [NULL, 20, 'Supports_this_item', 'Supports this item'],
            [NULL, 20, 'Leave_a_comment', 'Leave a comment, be nice'],

            [NULL, 20, 'Subtotal', 'Subtotal'],

            [NULL, 20, 'package_plan_page_subtitle', 'Lights tree our winged fifth his creepeth had herb kind life very very make so  harth face male'],
            [NULL, 20, 'Get_your_right_choice', 'Get your right choice'],

            [NULL, 20, 'product_header_sub_title', 'Crafty is an element gallery for web designers and web developers, anybody using
                            Bootstrap'],
            [NULL, 20, 'compatiability', 'Compatiability'],
            [NULL, 20, 'in_the_last', 'In the Last'],
            [NULL, 20, 'DiscoverOLDG', 'Discover Our Latest Digital Goods'],
            [NULL, 20, 'Low_to_High', 'Low to High'],
            [NULL, 20, 'High_to_Low', 'High to Low'],
            [NULL, 0, 'Created', 'Created'],
            [NULL, 0, 'resolution', 'Resolution'],
            [NULL, 0, 'reminders', 'reminders'],
            [NULL, 0, 'send_email_reminding', 'Send an email reminding me to rate an item a week after purchase'],
            [NULL, 0, 'Widget', 'Widget'],
            [NULL, 0, 'Ready', 'Ready'],
            [NULL, 0, 'sent', 'Sent'],
            [NULL, 0, 'main', 'Main'],
            [NULL, 0, 'Refund', 'Refund'],
            [NULL, 0, 'Reason', 'Reason'],
            [NULL, 0, 'Compatible', 'Compatible'],
            [NULL, 0, 'Browsers', 'Browsers'],
            [NULL, 0, 'What_are_my_Options', 'What are my Options?'],
            [NULL, 0, 'With', 'With'],
            [NULL, 0, 'request', 'Request'],
            [NULL, 0, 'decline', 'Decline'],
            [NULL, 0, 'give', 'Give'],
            [NULL, 0, 'next', 'Next'],
            [NULL, 0, 'payout', 'Payout'],
            [NULL, 0, 'pay', 'Pay'],
            [NULL, 0, 'via', 'Via'],
            [NULL, 0, 'or', 'Or'],
            [NULL, 0, 'Reply_to_Comment', 'Reply to Comment'],
            [NULL, 0, 'Framework', 'Framework'],
            [NULL, 0, 'Future', 'Future'],
            [NULL, 0, 'expire', 'Expire'],
            [NULL, 0, 'Quality_checked_by', 'Quality checked by'],
            [NULL, 0, 'Theme', 'Theme'],
            [NULL, 0, 'hosting', 'hosting'],
            [NULL, 0, 'hosting', 'hosting'],
            [NULL, 0, 'offer', 'offer'],
            [NULL, 0, 'Extend_support_to', 'Extend support to'],
            [NULL, 0, 'get_it_now', 'Get it now and save up to'],
            [NULL, 0, 'Add_To_Cart', 'Add To Cart'],
            [NULL, 0, 'Buy', 'Buy'],
            [NULL, 0, 'star', 'Star'],
            [NULL, 0, 'send', 'Send'],
            [NULL, 0, 'message', 'Message'],
            [NULL, 0, 'Now', 'Now'],
            [NULL, 0, 'graph', 'Graph'],
            [NULL, 0, 'notification', 'notification'],
            [NULL, 0, 'notifications', 'notifications'],
            [NULL, 0, 'Send_an_email_when_an_item_purchased_updated', 'Send an email when an item purchased is updated'],
            [NULL, 0, 'backup_settings', 'Backup Settings'],
            [NULL, 0, 'download', 'Download'],
            [NULL, 0, 'backup_files', 'Backup files'],
            [NULL, 0, 'created_date_time', 'CREATED DATE TIME'],
            [NULL, 0, 'address_recipeint', 'Your email address will be shown to the recipeint'],
            [NULL, 0, 'extended', 'Extended'],
            [NULL, 0, 'my', 'My'],
            [NULL, 0, 'team', 'Teamy'],
            [NULL, 0, 'send_notification_for_purchase', 'Send an email reminding me to rate an item a week after purchase'],
            [NULL, 0, 'comment_notification', 'Send me an email when someone comments on one of my items'],
            [NULL, 0, 'requirements', 'Requirements'],
            [NULL, 0, 'profile_update_message', 'We do not sell or share your details without your permission. Find out more in our Privacy Policy. Your username, email and password can be updated via your Codepixar Account settings'],
            [NULL, 0, 'tax', 'tax'],
            [NULL, 0, 'Already_Added_This_Item', 'Already Added This Item'],
            [NULL, 0, 'portfolio', 'Portfolio'],
            [NULL, 0, 'unfollow', 'Unfollow'],
            [NULL, 0, 'follow', 'Follow'],
            [NULL, 0, 'your', 'Your'],
            [NULL, 0, 'top', 'Top'],
            [NULL, 0, 'tons_of_premium', 'Tons of premium'],
            [NULL, 0, 'templates_are', 'Templates are'],
            [NULL, 0, 'template', 'Template'],
            [NULL, 0, 'waiting_for_you', 'Waiting for you!'],
            [NULL, 0, 'there_are_advances_being_made_in_science', 'There are advances being made in science'],
            [NULL, 0, 'technology_and_good', 'and technology everyday, and a good'],
            [NULL, 0, 'example_of', 'example of this is the'],
            [NULL, 0, 'countries', 'Countries'],
            [NULL, 0, 'set', 'Set'],
            [NULL, 0, 'set', 'Set'],
            [NULL, 0, 'backup', 'Backup'],
            [NULL, 0, 'earnings', 'Earnings'],
            [NULL, 0, 'this', 'this'],
            [NULL, 0, 'this_overview', 'this overview'],
            [NULL, 0, 'account', 'Account'],
            [NULL, 0, 'message_for_rating', 'to help the author Improve this iteam , please leave a resone and a comment for young rating'],
            [NULL, 0, 'ysreotl30d', 'Your sales and referral earnings over the last 30 days'],
            [NULL, 0, 'we_do_not_sell', 'We do not sell or share your details without your permission. Find out more in our Privacy Policy. Your username, email and password'],
            [NULL, 0, 'Upload_Your_First_Item', 'Upload Your First Item'],
            [NULL, 0, 'database_backup_list', 'Database Backup List'],
            [NULL, 0, 'welcome_for_author', 'Welcome and congratulations on becoming an author'],
            [NULL, 0, 'with_Infix_Digital_Marketplace', 'with Infix Digital Marketplace'],
            [NULL, 0, 'welcome_message_for_vendor', 'We do not sell or share your details without your permission. Find out more in our Privacy Policy. Your username, email
                                                                    and password can be updated via your Codepixar Account settings'],
            [NULL, 0, 'upload_from_local_directory', 'Upload From Local Directory'],
            [NULL, 0, 'All_prices_are', 'All prices are in USD'],
            [NULL, 0, 'regular_license_description', 'Chances are unless you are very lucky you will go thru many different relationships before you find your special someone'],
            [NULL, 0, 'extended_license_description', 'Chances are unless you are very lucky you will go thru many different relationships before you find your special someone'],
            [NULL, 0, 'itemsale', 'Item Sales Count'],
            [NULL, 0, 'tax', 'Tax'],
            [NULL, 0, 'ticket', 'Ticket'],
            [NULL, 0, 'choose', 'Choose'],
            [NULL, 0, 'your', 'Your'],
            [NULL, 0, 'purchase', 'Purchase'],
            [NULL, 0, 'submit_separate', 'If you need to refunds for multiple purchase then you will have to submit separate requests'],
            [NULL, 0, 'main_reason', 'Main reason for requesting a refund'],
            [NULL, 0, 'describe_details', 'Describe your request'],
            [NULL, 0, 'send_request', 'Send request'],
            [NULL, 0, 'reason_request', 'Your refund request will be sent to the author for review.They may get in touch with you to discuss details of the request'],
            [NULL, 0, 'dont_item', 'You dont have any refundable'],
            [NULL, 0, 'refund', 'Refund'],
            [NULL, 0, 'your_email address_recipeint', 'Your email address recipeint'],
            [NULL, 0, 'request_refund', 'Request A Refund'],
            [NULL, 0, 'reason_request', 'You dont have any refundable'],
            [NULL, 0, 'counter', 'Countery'],
            [NULL, 0, 'ticket_category', 'Ticket Category'],
            [NULL, 0, 'category_list', 'Category List'],
            [NULL, 0, 'ticket_system', 'Ticket System'],
            [NULL, 0, 'order', 'Order'],
            [NULL, 0, 'approve', 'Approve'],
            [NULL, 0, 'are_you_want_to_Approve', 'Are you want to approve this item'],
            [NULL, 0, 'are_you_want_to_deactive', 'Are you want to de-active this item'],
            [NULL, 0, 'are_you_want_to_suspent', 'Are you want to suspend this item'],
            [NULL, 0, 'affiliate', 'Affiliate'],
            [NULL, 0, 'added_time', 'Added time'],
            [NULL, 0, 'all', 'All'],
            [NULL, 0, 'link', 'Link'],
            [NULL, 0, 'ticket_list', 'ticket list'],
            [NULL, 0, 'country', 'Country'],
            [NULL, 0, 'state', 'State'],
            [NULL, 0, 'submit', 'Submit'],
            [NULL, 0, 'subject', 'subject'],
            [NULL, 0, 'department', 'Department'],
            [NULL, 0, 'search', 'search'],
            [NULL, 0, 'departments', 'Departments'],
            [NULL, 0, 'select_status', 'select status'],
            [NULL, 0, 'ticket_priority', 'Ticket Priority'],
            [NULL, 0, 'ticket_category', 'Ticket Category'],
            [NULL, 0, 'department_name', 'Department name'],
            [NULL, 0, 'marital_status', 'Marital Status'],
            [NULL, 0, 'married', 'Married'],
            [NULL, 0, 'unmarried', 'Unmarried'],
            [NULL, 0, 'select_criteria', 'Select Criteria'],
            [NULL, 0, 'search_by_name', 'Search By Name'],
            [NULL, 0, 'search_by_email', 'Search By Email'],
            [NULL, 0, 'position', 'Position'],
            [NULL, 0, 'custom', 'Custom'],
            [NULL, 0, 'links', 'Links'],
            [NULL, 0, 'page', 'Page'],
            [NULL, 0, 'welcome_message_for_vendor_billing_info', 'We do not sell or share your details without your permission. Find out more in our Privacy Policy.'],

            [NULL, 0, 'shopping_cart', 'Shopping Cart'],
            [NULL, 0, 'price_displayed_excludes_sales_tax', 'Price Displayed includes sales tax'],
            [NULL, 0, 'continue_shopping', 'Continue Shopping'],
            [NULL, 0, 'empty_cart', 'Empty Cart'],
            [NULL, 0, 'apply', 'Apply'],
            [NULL, 0, 'empty', 'Empty'],
            [NULL, 0, 'secure_checkout', 'Secure Checkout'],
            [NULL, 0, 'first_name', 'First Name'],
            [NULL, 0, 'site_key', 'Site key'],
            [NULL, 0, 'secret_key', 'Secret key'],
            [NULL, 0, 'company_name', 'Company name'],
            [NULL, 0, 'country_name', 'Country Name'],
            [NULL, 0, 'your_cart_total_is', 'Your Cart Total is'],
            [NULL, 0, 'billing_details', 'Billing Details'],
            [NULL, 0, 'city', 'City'],
            [NULL, 0, 'your_order', 'Your Order'],
            [NULL, 0, 'procced_to_payment', 'Procced to Payment'],
            [NULL, 0, 'zip_postal_code', 'Zip/Postal code'],
            [NULL, 0, 'you_can_buy_now', 'You can  buy now'],
            [NULL, 0, 'card_holder_name', 'Card Holder Name'],
            [NULL, 0, 'expiry_date', 'Expiry Date'],
            [NULL, 0, 'card_CVV', 'Card CVV'],
            [NULL, 0, 'save_for_next_time', 'Save for next time'],
            [NULL, 0, 'make_ayment', 'Make Payment'],
            [NULL, 0, 'sort_description', 'Sort Description'],
            [NULL, 0, 'long_description', 'Long Description'],
            [NULL, 0, 'go_to_item_Support', 'go to item Support'],
            [NULL, 0, 'extended', 'Extended'],
            [NULL, 0, 'limit', 'Limit'],
            [NULL, 0, 'main_file_message', 'ZIP - All files for buyers, not including preview images.'],
            [NULL, 0, 'maximum_file_size_allowed_500MB', 'The maximum file size allowed is 500 MB - please ensure compression has been optimized before uploading.'],
            [NULL, 0, 'tags_message', 'Maximum of 15 keywords covering features, usage, and styling. Keywords should all be in lowercase and separated by commas. e.g. photography, gallery, modern, jquery, wordpress theme.'],
            [NULL, 0, 'price_message', 'The "Recommended purchase price" is just a guide to help you decide - all pricing decisions are yours and yours only.'],
            [NULL, 0, 'submit_message', 'Any images, sounds, video, code, flash, or other assets that are not my own work, have been appropriately licensed for use in the file preview or main download. Other than these items, this work is entirely my own and I have full rights to sell it on'],
            [NULL, 0, "upload_heading", "It's important that you set the price for your items independently and not discuss your pricing decisions with other authors. The item price will include your author fee and your initial term of item support (if you offer it). See our Author Terms and Item Support breakdown if you want to know more"],
            [NULL, 0, 'thumdnail_message', 'JPEG or PNG 80x80px Thumbnail'],
            [NULL, 0, 'theme_preview_message', 'ZIP file of images (png/jpg)
            The first image appears on the Item Page and Search Results and must be 590x300 pixels and named 01_<filename>.jpg. You can include additional images which show off your item. Additional images must be named in the order that you want them to appear, for example, 02_<filename>.jpg, 03_<filename>.jpg, 04_<filename>.jpg. These images can be a maximum of 900x900 pixels, and may be cropped when displayed on the search results page to the same aspect ratio as the main preview image. Images must be JPGs or PNGs.'],
            [NULL, 0, 'key_feature_messsage', 'Highlight what makes your item unique or a key selling point. They appear on search result pages next to an image of your item. Max 45 characters per line. No HTML or emoji allowed. Do not repeat features or keyword spam.'],
            [NULL, 0, "key_feature_messsage_description", "HTML or plain text allowed, no emoji This field is used for search, so please be descriptive! If you're linking to external images, please mind the page load speed: use few, compress them and host them on a fast server or CDN."],
            [NULL, 0, 'Contact_the_author', 'Contact the author'],
            [NULL, 0, 'this_author_will_respond', 'This author will respond to buyers questions and provides limited support through their own support system.'],
            [NULL, 0, 'authors', 'Authors'],
            [NULL, 0, 'front_settings', 'Front Settings'],
            [NULL, 0, 'footer_menu', 'Footer Menus'],
            [NULL, 0, 'feature_title', 'Feature Title'],
            [NULL, 0, 'menu_title', 'Menu Title'],
            [NULL, 0, 'menu_url', 'Menu URL'],
            [NULL, 0, 'menu', 'Menu'],
            [NULL, 0, 'progress', 'Progress'],
            [NULL, 0, 'your_shopping_cart_is_empty', 'Your Shopping Cart is Empty.'],
            [NULL, 0, 'search_box_color', 'Search Box Color'],
            [NULL, 0, 'background_color', 'Background Color'],
            [NULL, 0, 'front_settings', 'Front Settings'],
            [NULL, 0, 'footer_menu_ist', 'Footer Menu List'],
            [NULL, 0, 'footer_menu_ist', 'Footer Menu List'],
            [NULL, 0, 'footer_menu', 'Footer Menu'],
            [NULL, 0, 'category_limit', 'Category limit'],
            [NULL, 0, 'home_page', 'Home Page'],
            [NULL, 0, 'Home_page', 'Home Page'],
            [NULL, 0, 'feature', 'Feature'],
            [NULL, 0, 'expired_coupon', 'Expired Coupon'],
            [NULL, 0, 'delete_coupon', 'Delete Coupon'],
            [NULL, 0, 'add_coupon', 'Add Coupon'],
            [NULL, 0, 'heading_text', 'Heading Text'],
            [NULL, 0, 'fund', 'Fund'],
            [NULL, 0, 'depositor', 'depositor'],
            [NULL, 0, 'receiver', 'receiver'],
            [NULL, 0, 'note', 'note'],
            [NULL, 0, 'funding_history', 'Fund History'],

            [NULL, 0, 'ticket_text', 'Ticket Text'],
            [NULL, 0, 'ip', 'IP'],
            [NULL, 0, 'admin_profile', 'Admin Profile'],
            [NULL, 0, 'priority_list', 'Priority List'],
            [NULL, 0, 'staff', 'Staff'],
            [NULL, 0, 'change_your_password', 'Change your password.'],
            [NULL, 0, 'move_to', 'Move To'],
            [NULL, 0, 'recommended', 'Recommended'],
            [NULL, 0, 'profile_setting', 'Profile Setting'],
            [NULL, 0, 'text', 'Text'],
            [NULL, 0, 'last_name', 'Last Name'],
            [NULL, 0, 'region', 'Region'],
            [NULL, 0, 'money', 'Money'],
            [NULL, 0, 'agent', 'Agent'],
            [NULL, 0, 'group', 'Group'],
            [NULL, 0, 'individual', 'Individual'],
            [NULL, 0, 'revenue', 'Revenue'],
            [NULL, 0, 'extend_support_Fee', 'Extend Support Fee'],
            [NULL, 0, 'role_permission', 'Pole Permission'],
            [NULL, 0, 'assign_permission', 'Assain Permission'],
            [NULL, 0, 'system', 'System'],
            [NULL, 0, 'font_awesome_icon', 'Font Awesome Icon'],
            [NULL, 0, 'social_url', 'Social URL'],
            [NULL, 0, 'refuse', 'Refuse'],
            [NULL, 0, 'owner', 'Owner'],
            [NULL, 0, 'created_at', 'Created At'],
            [NULL, 0, 'dipositor', 'Dipositor'],
            [NULL, 0, 'enter_email', 'Enter Email'],
            [NULL, 0, 'test_mail_configuration', 'Test Mail Configuration'],
            [NULL, 0, 'test_mail', 'Test Mail'],
            [NULL, 0, 'to', 'To'],
            [NULL, 0, 'soft_rejected', 'Soft Rejected'],
            [NULL, 0, 'hard_rejected', 'Hard Rejected'],
            [NULL, 0, 'view_full_license', 'View full License'],
            [NULL, 0, 'market_apis', 'Market Apis'],
            [NULL, 0, 'package_plan', 'Package Plan'],
            [NULL, 0, 'per_month', 'Per Month'],
            [NULL, 0, 'talk_to_the_buyer', '1. Talk to the buyer to see if you can help them '],
            [NULL, 0, 'if_not_make', '2. If not, make a decision with the refund.'],
            [NULL, 0, 'downloaded', 'Downloaded'],
            [NULL, 0, 'not', 'Not'],
            [NULL, 0, 'your_comment', 'Your Comment'],
            [NULL, 0, 'live_review', 'Live Review'],
            [NULL, 0, 'screenshoot', 'Screenshoot'],
            [NULL, 0, 'item_support_policy', 'item support policy'],
            [NULL, 0, 'send_an_email_to_the_author', 'Send an email to The author'],
            [NULL, 0, 'all_messege_are_recorded', 'All messege are recorded ans spam is not tolerated. maximum word'],
            [NULL, 0, 'sign_in_to_download_it_for_free ', 'Sign in to download it for free '],
            [NULL, 0, 'view_license_details', 'View license details'],
            [NULL, 0, 'by_downloading_this_item', 'By downloading this item, you agree to the terms of the Regular License. Support and updates are not provided for free files.'],
            [NULL, 0, 'support_ticket', 'Support Ticket'],
            [NULL, 0, 'tickets', 'Tickets'],
            [NULL, 0, 'open_new_ticket', 'Open New Ticket'],
            [NULL, 0, 'view_ticket', 'View Ticket'],
            [NULL, 0, 'submitted', 'Submitted'],
            [NULL, 0, 'back', 'Back'],
            [NULL, 0, 'messege', 'Messege'],
            [NULL, 0, 'upload_an_image', 'Upload an image'],
            [NULL, 0, 'supported_extensions', 'supported extensions: .jpg, .gif, .jpeg, .png,.pdf, .doc, .docx, .xls, .xlsx, .csv, .sql, .txt, .html, .bmp,.zip,.tar.gz, .crt, .key, .ca-bundle'],
            [NULL, 0, 'attach_a_file', 'Attach a file'],
            [NULL, 0, 'open_ticket', 'Open Ticket'],
            [NULL, 0, 'related_service', 'Related Service'],
            [NULL, 0, 'open_a_new_tickets', 'Open a new Tickets'],
            [NULL, 0, 'last_updated', 'Last Updated'],
            [NULL, 0, 'ticket_id', 'Ticket ID'],
            [NULL, 0, 'no_sales', 'No Sales'],
            [NULL, 0, '1_star_and_higher', '1 Star and Higher'],
            [NULL, 0, '2_star_and_higher', '2 Star and Higher'],
            [NULL, 0, '3_star_and_higher', '3 Star and Higher'],
            [NULL, 0, '4_star_and_higher', '4 Star and Higher'],
            [NULL, 0, '5_star_and_higher', '5 Star and Higher'],
            [NULL, 0, 'date_added', 'Date Added'],
            [NULL, 0, 'software_version', 'Software Version'],
            [NULL, 0, 'add_invoice', 'Add Invoice'],
            [NULL, 0, 'total_community_earnings', 'Total Community Earnings'],
            [NULL, 0, 'total_items_sold', 'Total items sold'],
            [NULL, 0, 'start_selling', 'Start Selling'],
            [NULL, 0, 'view_portfolio', 'View Portfolio'],
            [NULL, 0, 'member_since', 'Member since'],
            [NULL, 0, 'total_sales', 'Total Sales'],
            [NULL, 0, 'deposit_amount', 'Deposit Amount'],
            [NULL, 0, 'postcode_ZIP', 'Postcode/ZIP'],
            [NULL, 0, 'select_package', 'Select Package'],
            [NULL, 0, 'get_package', 'get package'],
            [NULL, 0, 'you_have_appproved_this_refund', 'You Have appproved this refund'],
            [NULL, 0, 'product_features', 'Product features'],
            [NULL, 0, 'best_sellers', 'Best Sellers'],
            [NULL, 0, 'best_rated', 'Best Rated'],
            [NULL, 0, 'price_high_to_low', 'Price High to Low'],
            [NULL, 0, 'price_low_to_high', 'Price Low to High'],
            [NULL, 0, 'clear_filter', 'Clear Filter'],
            [NULL, 0, 'click_here', 'Click here'],
            [NULL, 0, 'mobile_no', 'Mobile No'],
            [NULL, 0, 'personal_info', 'Personal info'],
            [NULL, 0, 'please_input_time_yearly', 'Please input time yearly'],
            [NULL, 0, 'please_input', 'Please input 80*80 png or jpg'],
            [NULL, 0, 'offline_payment', 'Offline Payment'],
            [NULL, 0, 'bank_payment', 'Bank Payment'],
            [NULL, 0, 'approved_deposit_request', 'Approved Deposit Request'],
            [NULL, 0, 'bank_info', 'Bank Info'],
            [NULL, 0, 'account_no', 'Account No'],
            [NULL, 0, 'owner_name', 'Owner Name'],
            [NULL, 0, 'approved', 'Approved'],
            [NULL, 0, 'deposit', 'Deposit'],
            [NULL, 0, 'are_you_sure_to_approve_this_deposit_request', 'Are you sure to approve this deposit request'],
            [NULL, 0, 'bank_deposit_request', 'Bank Deposit Request'],
            [NULL, 0, 'license_feature', 'License Feature'],
            [NULL, 0, 'disable', 'Disable'],
            [NULL, 0, 'enable', 'Enable'],
            [NULL, 0, 'modules_list', 'Modules List'],
            [NULL, 0, 'visitor_and_page_view', 'Visitor and Page View'],
            [NULL, 0, 'new_client_information', 'New Client Information'],
            [NULL, 0, 'select_styles', 'Select Styles'],
            [NULL, 0, 'select_alignment', 'Select Alignment'],
            [NULL, 0, 'approved_request', 'Approved Request'],
            [NULL, 0, 'fund_list', 'Fund List'],
            [NULL, 0, 'add_fund', 'Add Fund'],
            [NULL, 0, 'author_balance', 'Author Balance'],
            [NULL, 0, 'RECM_extended', 'RECM Extended'],
            [NULL, 0, 'RECM_regular', 'RECM Regular'],
            [NULL, 0, 'RECM_commercial', 'RECM COMMERCIAL'],
            [NULL, 0, 'show_in_menu', 'Show In Menu'],
            [NULL, 0, 'product_free', 'Product free'],
            [NULL, 0, 'are_you_want_to_refund', 'Are you want to refund?'],
            [NULL, 0, 'assign_permission', 'Assign Permission'],
            [NULL, 0, 'new_saller', 'New Saller'],
            [NULL, 0, 'top_best_saller', 'Top Best Saller'],
            [NULL, 0, 'monthly_sales_report', 'Monthly Sales Report'],
            [NULL, 0, 'daily_sales_report', 'Daily Sales Report'],
            [NULL, 0, 'visitor_type', 'Visitor Type'],
            [NULL, 0, 'visitor_country', 'Visitor Country'],
            [NULL, 0, 'item_by', 'Item By'],
            [NULL, 0, 'this_item_is_now_available_on_your', 'This item is now available on your'],
            [NULL, 0, 'an_confirmation_email_is_coming_your_way', 'An confirmation Email is coming your way.'],
            [NULL, 0, 'payment_complete', 'Payment Complete'],
            [NULL, 0, 'to_see_this_item', 'To see this item'],
            [NULL, 0, 'click_here_to_request_another', 'Click here to request another'],
            [NULL, 0, 'before_proceeding', 'Before proceeding, please check your email for a varification link. If you din not get the email.'],
            [NULL, 0, 'verify_your_email_address', 'Verify Your Email Address'],
            [NULL, 0, 'mail_verify', 'Mail Verify'],
            [NULL, 0, 'view_all_free_products', 'View All Free Products'],
            [NULL, 0, 'free_product_of_the_month', 'Free product of the month'],
            [NULL, 0, 'view_all_featured_products', 'View All Featured Products'],
            [NULL, 0, 'continue', 'Continue'],
            [NULL, 0, 'by_continuing_you_agree_to_the', 'By continuing you agree to the'],
            [NULL, 0, 'become_an', 'Become an'],
            [NULL, 0, 'in_the_last', 'In the Last'],
            [NULL, 0, 'day', 'day'],
            [NULL, 0, 'select_city', 'Select City'],
            [NULL, 0, 'view_the', 'View the'],
            [NULL, 0, 'this_is_free_item_file_of_the_month', 'This is Free Item File of the Month'],
            [NULL, 0, 'compatible_with', 'Compatible with'],
            [NULL, 0, 'compatible_browsers', 'Compatible browsers'],
            [NULL, 0, 'high_resolution', 'High Resolution'],
            [NULL, 0, 'in', 'In'],
            [NULL, 0, 'sign_out', 'Sign Out'],
            [NULL, 0, 'payouts', 'Payouts'],
            [NULL, 0, 'statement', 'Statement'],
            [NULL, 0, 'settings', 'Settings'],
            [NULL, 0, 'user_settings', 'User Settings'],
            [NULL, 0, 'author_settings', 'Author Settings'],
            [NULL, 0, 'become_a_author', 'Become an Author'],
            [NULL, 0, 'balances', 'Balances'],
            [NULL, 0, 'sign_in', 'Sign In'],
            [NULL, 0, 'order_details', 'Order Details'],
            [NULL, 0, 'payouts2_tab', 'payouts2-tab'],
            [NULL, 0, 'payouts3_tab', 'Payouts3-tab'],
            [NULL, 0, 'your_stripe_account', 'Your Stripe Account'],
            [NULL, 0, 'minimum_amount_$50.00', 'Minimum amount $50.00'],
            [NULL, 0, 'name_of_account_owner', 'Name of account owner'],
            [NULL, 0, 'bank_name', 'Bank Name'],
            [NULL, 0, 'by_continuing_you_agree_to_the ', 'By continuing you agree to the '],
            [NULL, 0, '404_error_message_text ', '404 Error Message Text'],
            [NULL, 0, 'sign_in_page_message ', 'Sign In Page Message'],
            [NULL, 0, 'view_text ', 'View Text'],
            [NULL, 0, 'font_awesome_icon_list  ', 'Font Awesome Icon List'],
            [NULL, 0, 'complete  ', 'Complete'],
            [NULL, 0, 'this_application_will_be_able_to  ', 'This application will be able to'],
            [NULL, 0, 'is_requesting_permission_to_access_your_account.  ', 'is requesting permission to access your account.'],
            [NULL, 0, 'authorization_request.  ', 'Authorization Request'],
            [NULL, 0, 'module_humanResource.  ', 'Module HumanResource'],
            [NULL, 0, 'crop', 'Crop'],
            [NULL, 0, 'module_knowledgeBase', 'Module KnowledgeBase'],
            [NULL, 0, 'sub_question', 'Sub question'],
            [NULL, 0, 'module_mailSystem', 'Module MailSystem'],
            [NULL, 0, 'this_view_is_loaded_from_module', 'This view is loaded from module'],
            [NULL, 0, 'hello_world', 'Hello World'],
            [NULL, 0, 'module_newsletter', 'Module Newsletter'],
            [NULL, 0, 'module_pages', 'Module Pages'],
            [NULL, 0, 'become_author_text', 'Become Author Text'],
            [NULL, 0, 'update_item_support', 'Update Item Support'],
            [NULL, 0, 'license_feature_list', 'License Feature List'],
            [NULL, 0, 'module_refund', 'Module Refund'],
            [NULL, 0, 'module_tax', 'Module Tax'],
            [NULL, 0, 'download_file', 'Download file'],
            [NULL, 0, 'module_icket', 'Module Ticket'],
            [NULL, 0, 'module_systemsetting', 'Module Systemsetting'],
            [NULL, 0, 'system_activated_date', 'System Activated Date'],
            [NULL, 0, 'install_domain', 'Install Domain'],
            [NULL, 0, 'purchase_code', 'Purchase code'],
            [NULL, 0, 'curl_enable', 'Curl enable'],
            [NULL, 0, 'PHP_version', 'PHP Version'],
            [NULL, 0, 'Check_update', 'Check update'],
            [NULL, 0, 'size', 'Size'],
            [NULL, 0, 'database', 'Database'],
            [NULL, 0, 'full_project', 'Full Project'],
            [NULL, 0, 'images', 'Images'],
            [NULL, 0, 'auto_approval', 'Auto Approval'],
            [NULL, 0, 'auto_update', 'Auto Update'],
            [NULL, 0, 'setup_fixer', 'Setup Fixer'],
            [NULL, 0, 'fixer_access_key', 'Fixer Access Key'],
            [NULL, 0, 'setup_google_analytics', 'Setup Google Analytics'],
            [NULL, 0, 'GOOGLE_ANALYTICS_VIEW_ID', 'GOOGLE ANALYTICS VIEW ID'],
            [NULL, 0, 'setup_third_party_APIs', 'Setup Third Party APIs'],
            [NULL, 0, 'third_party_API', 'Third Party API'],
            [NULL, 0, 'phrases', 'Phrases'],
            [NULL, 0, 'default_phrases', 'Default Phrases'],
            [NULL, 0, 'activated', 'Activated'],
            [NULL, 0, 'live', 'Live'],
            [NULL, 0, 'sandbox', 'Sandbox'],
            [NULL, 0, 'LTL', 'LTL'],
            [NULL, 0, 'RTL', 'RTL'],
            [NULL, 0, 'footer_custom_link', 'Footer Custom Link'],
            [NULL, 0, 'site_image_settings', 'Site Image Settings'],
            [NULL, 0, 'about_company', 'About Company'],
            [NULL, 0, 'become_author', 'Become Author'],
            [NULL, 0, 'item_support', 'Item Support'],
            [NULL, 0, 'terms_conditions', 'Terms & Conditions'],
            [NULL, 0, 'privacy_policy', 'Privacy Policy'],
            [NULL, 0, 'frontend_CMS', 'Frontend CMS'],
            [NULL, 0, 'dashboard_themes', 'Dashboard Themes'],
            [NULL, 0, 'SEO_settings', 'SEO Settings'],
            [NULL, 0, 'payment_method_settings ', 'Payment Method Settings'],
            [NULL, 0, 'role_permission ', 'Role Permission'],
            [NULL, 0, 'general_settings ', 'General Settings'],
            [NULL, 0, 'inventory ', 'Inventory'],
            [NULL, 0, 'logout ', 'Logout'],
            [NULL, 0, 'set_date ', 'Set Date'],
            [NULL, 0, 'start_date ', 'Start Date'],
            [NULL, 0, 'end_date ', 'End Date'],
            [NULL, 0, 'enter_coupon_code ', 'Enter Coupon Code'],
            [NULL, 0, 'payPal_accepts ', 'PayPal accepts'],
            [NULL, 0, 'use ', 'Use'],
            [NULL, 0, 'from_my_infix_balance_for_this_purchase ', 'from my infix balance for this purchase'],
            [NULL, 0, 'statements ', 'Statements'],
            [NULL, 0, 'refunds ', 'Refunds'],
            [NULL, 0, 'hidden_items ', 'Hidden Items'],
            [NULL, 0, 'social_profiles ', 'Social Profiles'],
            [NULL, 0, 'regular_license_with ', 'Regular License with help wordpress file installation'],
            [NULL, 0, 'get_notified ', 'Get Notified by email if this item is updated'],
            [NULL, 0, 'support_will_expair ', 'support will expair'],
            [NULL, 0, 'all_files_documentation ', 'All files & documentation'],
            [NULL, 0, 'installable_file_only ', 'Installable file only'],
            [NULL, 0, 'license_certificate_purchase_code', 'License certificate & purchase code (pdf)'],
            [NULL, 0, 'reviewed_by', 'Reviewed by'],
            [NULL, 0, 'no_refund_request', 'No Refund Request'],
            [NULL, 0, 'minimum_amount', 'Minimum amount'],
            [NULL, 0, 'xtemos', 'Xtemos'],
            [NULL, 0, 'woodMark_responsive_woocommerce_theme', 'woodMark - responsive Woocommerce theme'],
            [NULL, 0, 'fees', 'Fees'],
            [NULL, 0, 'my_funds', 'My Funds'],
            [NULL, 0, 'total_value_of_your_sales', 'Total value of your sales, before author fees (based on list price)'],
            [NULL, 0, 'your_total_balance_after_associated_author_fees', 'Your total balance after associated author fees'],
            [NULL, 0, 'setup_account', 'Setup Payout Account'],
            [NULL, 0, 'add_a_new_razorPay_account', 'Add a New RazorPay Account'],
            [NULL, 0, 'more_about_razorPay', 'More about RazorPay'],
            [NULL, 0, 'razorPay_international_transfer', 'RazorPay (International Transfer)get paid directly into your bank account. Connected with over 9000 banking organisations, security institutions and customers in more than 200 countries'],
            [NULL, 0, 'your_razorPay_account', 'Your RazorPay Account'],
            [NULL, 0, 'create_an_account', 'Create an account'],
            [NULL, 0, 'more_about_payPal', 'More about PayPal'],
            [NULL, 0, 'get_paid_by_credit', 'Get paid by credit or debit card, PayPal transfer or even via bank account in just a few clicks.All you need is your email address or mobile number.'],
            [NULL, 0, 'your_paypal_account', 'Your Paypal Account'],
            [NULL, 0, 'more_about_stripe', 'More about Stripe'],
            [NULL, 0, 'get_paid_by_credit_or', 'Get paid by credit or debit card, Stripe transfer or even via bank account in just a few clicks.All you need is your email address or mobile number.'],
            [NULL, 0, 'your_stripe_account', 'Your Stripe Account'],
            [NULL, 0, 'item_price', 'Item price'],
            [NULL, 0, 'no_item', 'No Item'],
            [NULL, 0, 'resubmit', 'Resubmit'],
            [NULL, 0, 'product_validation', 'Product Validation'],
            [NULL, 0, 'API_path', 'API Path'],
            [NULL, 0, 'copy_text', 'Copy Text'],
            [NULL, 0, 'genarate_API_key', 'Genarate API Key'],
            [NULL, 0, 'CVC_number', 'CVC Number'],
            [NULL, 0, 'expire_date', 'Expire Date'],
            [NULL, 0, 'card_umber', 'Card Number'],
            [NULL, 0, 'send_me_a_daily_summary', 'Send me a daily summary of all items approved or rejected'],
            [NULL, 0, 'item_purchase_date', 'Item Purchase Date'],
            [NULL, 0, 'item_purchase_code', 'Item Purchase Code'],
            [NULL, 0, 'item_ID', 'Item ID'],
            [NULL, 0, 'item_URL', 'Item URL'],
            [NULL, 0, 'item_title', 'Item Title'],
            [NULL, 0, 'licensors_author_username', 'Licensors Author Username'],
            [NULL, 0, 'license_certificate', 'License Certificate'],
            [NULL, 0, 'valid_date', 'Valid Date'],
            [NULL, 0, 'coupon_code', 'Coupon Code'],
            [NULL, 0, 'coupon_name', 'Coupon Name'],
            [NULL, 0, 'coupon_list', 'Coupon list'],
            [NULL, 0, 'coupon_item', 'Coupon Item'],
            [NULL, 0, 'min_valid_rice', 'Min. Valid Price'],
            [NULL, 0, 'discounted_amount', 'Discounted Amount'],
            [NULL, 0, 'coupon_type', 'Coupon Type'],
            [NULL, 0, 'inactive_coupons', 'Inactive Coupons'],
            [NULL, 0, 'expired_coupons', 'Expired Coupons'],
            [NULL, 0, 'restore', 'Restore'],
            [NULL, 0, 'deleted_coupons', 'Deleted Coupons'],
            [NULL, 0, 'enter_discount_rate', 'Enter discount rate'],
            [NULL, 0, 'percent', 'Percent'],
            [NULL, 0, 'fixed', 'Fixed'],
            [NULL, 0, 'coupon_discount', 'Coupon Discount'],
            [NULL, 0, 'multiple', 'Multiple'],
            [NULL, 0, 'once', 'Once'],
            [NULL, 0, 'all_coupons', 'All Coupons'],
            [NULL, 0, 'all_active_coupons', 'All Active Coupons'],
            [NULL, 0, 'help', 'Help'],
            [NULL, 0, 'select_category', 'Select Category'],
            [NULL, 0, 'select_switch_ategories', 'Select/switch Categories'],
            [NULL, 0, 'upload_item', 'Upload Item'],
            [NULL, 0, 'name_and_desription', 'Name and Desription'],
            [NULL, 0, 'message_to_the_reviewer', 'Message to the Reviewer'],
            [NULL, 0, 'purchase_price', 'Purchase price'],
            [NULL, 0, 'BUYER_FEE', 'BUYER FEE'],
            [NULL, 0, 'ITEM_PRISE', 'ITEM PRISE'],
            [NULL, 0, 'extended_license', 'Extended License'],
            [NULL, 0, 'regular_license', 'regular license'],
            [NULL, 0, 'N/A', 'N/A'],
            [NULL, 0, 'responsive', 'Responsive'],
            [NULL, 0, 'liquid', 'Liquid'],
            [NULL, 0, 'widget_ready', 'Widget Ready'],
            [NULL, 0, 'categories_and_attributes', 'Categories and Attributes'],
            [NULL, 0, 'ZIP_containing_an_installable', 'ZIP containing an installable'],
            [NULL, 0, 'browse_file', 'Browse File'],
            [NULL, 0, 'mark_all_images', 'Mark all images and make it zip. Please dont zip a folder.'],
            [NULL, 0, 'theme_preview', 'Theme Preview'],
            [NULL, 0, 'thumbnails', 'Thumbnails'],
            [NULL, 0, 'maximum_100_characters_no_HTML_r_emoji_allowed', 'Maximum 100 characters. No HTML or emoji allowed'],
            [NULL, 0, 'demo_url', 'Demo url'],
            [NULL, 0, 'main_files', 'Main Files'],
            [NULL, 0, 'your_previous_update_is_pending', 'Your previous update is pending, Please wait till get approval'],
            [NULL, 0, 'images_found', 'images found'],
            [NULL, 0, 'key_features', 'Key Features'],
            [NULL, 0, 'search_your_product', 'Search your product'],
            [NULL, 0, 'phone_number', 'Phone number'],
            [NULL, 0, 'user_name', 'User name'],
            [NULL, 0, 'confirm_password', 'Confirm Password'],
            [NULL, 0, 'new_password', 'New Password'],
            [NULL, 0, 'current_password', 'Current Password'],
            [NULL, 0, 'enter_email_address', 'Enter email address'],
            [NULL, 0, 'enter_fix_discount', 'Enter fix discount'],
            [NULL, 0, 'to_date', 'To date'],
            [NULL, 0, 'from_date', 'From date'],
            [NULL, 0, 'full_name', 'Full Name'],
            [NULL, 0, 'confirm_passowrd', 'Confirm Passowrd'],
            [NULL, 0, 'enter_passowrd', 'Enter passowrd'],
            [NULL, 0, 'username_email_address', 'Username / Email address'],
            [NULL, 0, 'enter_username', 'Enter username'],
            [NULL, 0, 'enter_full_name', 'Enter full name'],
            [NULL, 0, 'enter_valid_email', 'Enter valid Email'],
            [NULL, 0, 'froget_password', 'Froget Password'],
            [NULL, 0, 'f_id', 'F-ID'],
            [NULL, 0, 'there_are_no_comments_for_this_item_yet', 'There are no comments for this item yet'],
            [NULL, 0, 'no_review_available', 'No Review Available'],
            [NULL, 0, 'purchased', 'Purchased'],
            [NULL, 0, 'supported', 'Supported'],
            [NULL, 0, 'Upload_From_Local_Directory', 'Upload From Local Directory'],
        ];

        $translates = [];
        foreach ($all_translate as $row) {
            $translates[] = [
                'id' => $row[0],
                'modules' => $row[1],
                'default_phrases' => trim($row[2]),
                'en' => trim($row[3]),
            ];
        }

        DB::table('sm_language_phrases')->insert($translates);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sm_language_phrases');
    }
}
